# Generated by Django 4.2.1 on 2023-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.TextField()),
                ('subjects', models.TextField()),
                ('by_user', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('images', models.TextField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
