# Generated by Django 4.2.1 on 2023-08-11 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_remove_post_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.TextField(default='Insert Image Here'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Insert Text Here'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Insert Title Here', max_length=50),
        ),
    ]
