# Generated by Django 4.2.1 on 2023-08-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0004_alter_post_dislikes_alter_post_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
