# Generated by Django 4.2.1 on 2023-08-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_post_current_user_alter_post_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='current_user',
        ),
    ]
